const themeVariables = {
	light: { 
		'--primary-color': '#007BFF',
		'--primary-background': '#FFFFFF',
		'--light-background': '#FFFFFF',
		'--element-background': '#F7F7F7',
		'--text-primary': '#343A40',
		'--text-secondary': '#6C757D',
		'--text-color': '#FFFFFF',
		'--hover-background': '#0056B3',
		'--hover-secondary-background': '#E2E2E2',
		'--button-primary-bg': '#007BFF',
		'--button-primary-text': '#FFFFFF',
		'--button-hover-bg': '#0056B3',
		'--button-hover-text': '#FFFFFF',
		'--shadow-soft': '0px 4px 8px rgba(0, 0, 0, 0.1)',
		'--shadow-hover': '0px 6px 12px rgba(0, 0, 0, 0.2)',
		'--transform-scale-hover': 'scale(1.05)',
		'--font-family': 'Roboto, sans-serif',
		'--font-size': '14px',
        '--font-weight': '400',
        '--font-weight-bold': '700',
        '--font-weight-semi-bold': '600',
        '--font-weight-light': '300',
	},
	dark: {
		'--primary-color': '#333333',
		'--primary-background': '#121212',
		'--light-background': '#333333',
		'--element-background': '#121212',
		'--text-primary': '#FFFFFF',
		'--text-secondary': '#6C757D',
		'--text-color': '#FFFFFF',
		'--hover-background': '#0056B3',
		'--hover-secondary-background': '#E2E2E2',
		'--button-primary-bg': '#333333',
		'--button-primary-text': '#FFFFFF',
		'--button-hover-bg': '#0056B3',
		'--button-hover-text': '#FFFFFF',
		'--shadow-soft': '0px 4px 8px rgba(0, 0, 0, 0.1)',
		'--shadow-hover': '0px 6px 12px rgba(0, 0, 0, 0.2)',
		'--transform-scale-hover': 'scale(1.05)',
	},
};

export default themeVariables;
